#! /bin/sh

headers='Langau.h'

cat > LinkDef.h <<END

#ifdef __CINT__

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

#pragma link C function langaufit;
#pragma link C function langaufun;
#pragma link C function langaupro;

#endif
END

hlast=LinkDef.h

rm -f $1

rootcint $1 -c $headers $hlast



